name: Teardown Resources

on:
  workflow_dispatch:

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: "latest"
          skip_install: false

      - name: Run teardown script
        run: |
          chmod +x teardown.sh
          ./teardown.sh
